# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('defBank', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='CDV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=30)),
                ('checkAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkNo', models.CharField(max_length=30)),
                ('pubDateCDV', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=150)),
                ('totalAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.Branch')),
            ],
            options={
                'verbose_name_plural': 'Cash Disbursement Vouchers',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accGrpentry', models.CharField(max_length=50)),
                ('accCode', models.IntegerField(default=0)),
                ('accDescrip', models.CharField(max_length=50)),
                ('accEntry', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('branch', models.ManyToManyField(to='acctsys.Branch')),
            ],
            options={
                'verbose_name_plural': 'Chart Of Accounts',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Crews',
            },
        ),
        migrations.CreateModel(
            name='CRV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedFr', models.CharField(max_length=20)),
                ('pubDateCRV', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=150)),
                ('totalAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.Branch')),
            ],
            options={
                'verbose_name_plural': 'Cash Receipt Vouchers',
            },
        ),
        migrations.CreateModel(
            name='JV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDateJV', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=150)),
                ('totalAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.Branch')),
            ],
            options={
                'verbose_name_plural': 'Journal Vouchers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpCode', models.CharField(max_length=50)),
                ('prodCode', models.IntegerField(default=0)),
                ('prodDescrip', models.CharField(max_length=50)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchaseAmt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actualStock', models.DecimalField(decimal_places=2, max_digits=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.Branch')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodCategory', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Product Lists',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginBal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incoming', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('availBal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endBal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actualCount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shortOrOver', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salesAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchaseAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shortOrOverAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('netAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashOnHand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashInBank', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.Branch')),
                ('coa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.ChartOfAccounts')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.Crew')),
                ('crv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acctsys.CRV')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='VoucherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctCode', models.IntegerField(default=0)),
                ('acctDescrip', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Voucher Info',
            },
        ),
        migrations.AddField(
            model_name='jv',
            name='vInfo',
            field=models.ManyToManyField(to='acctsys.VoucherInfo'),
        ),
        migrations.AddField(
            model_name='crv',
            name='vInfo',
            field=models.ManyToManyField(to='acctsys.VoucherInfo'),
        ),
        migrations.AddField(
            model_name='cdv',
            name='vInfo',
            field=models.ManyToManyField(to='acctsys.VoucherInfo'),
        ),
    ]
